name: Lints

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lints
    steps:
      - uses: actions/checkout@v2
      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
