name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.3'
      - run: swift test
